### PR TITLE
Adds Discord Notifications

### PR DESCRIPTION
**Pull request by night**
This pull request adds the ability to send build status updates to Discord via webhooks.

The configuration format looks like the following:

``` YAML
notifications:
  discord:
    channels:
      - [webhook_id]:[webhook_token]
      - [webhook_id_2]:[webhook_token_2]
    pull_request_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} in PR [#%{pull_request_number}](%{pull_request_url}) by %{author} %{result} in %{duration}'
    branch_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} by %{author} %{result} in %{duration}'
```

Related PRs:
~~https://github.com/travis-ci/travis-core/issues/562~~
https://github.com/travis-ci/travis-tasks/issues/71
https://github.com/travis-ci/docs-travis-ci-com/pull/1133

### CODE REVIEW

**Comment by AraHaan** [comment]
Night what about securly encrypted webhook tokens? would it handle that case?

**Comment by night** [comment]
@AraHaan you would encrypt the `[id]:[token]` in your `travis.yml` as per usual

**Comment by AraHaan** [comment]
Seems good.

**Comment by BanzaiMan** [comment]
I am sorry, but this has been put on hold for the time being. (https://github.com/travis-ci/travis-tasks/pull/71#issuecomment-294579129)

**Comment by AraHaan** [comment]
I should be able to be merged now because of the PR to https://github.com/travis-ci/docs-travis-ci-com/pull/1133 was opened like 9 hours ago.

**Comment by Brodan** [comment]
Hey @night, I'm interested in creating a similar feature, only with Twilio instead of Discord. Any idea on to test and build this stuff locally? Did you rely purely on unit tests before opening your PRs?

**Comment by jaydenkieran** [comment]
Hey @BanzaiMan, we're into 2018 now and this (and associated PRs) have been open since Oct 2016, so I was wondering if there's any further progress on this? I'm aware that you put it on hold, but that was in April last year with no explanation.

I know a few developers that use Travis and have moved from Slack to Discord. CI notifications into a Discord channel would be super helpful to those people, and many others, so I don't really understand why this integration hasn't been added yet. Can you provide an update as to the status of this?

**Comment by AraHaan** [comment]
I used to use travis but due to the lack of this since moved to github actions because of built-in support for Discord notifications.

**Pull request closed without merging**
