### PR TITLE
Skip unsubscribed users when sending build emails

### PR DESCRIPTION
**Pull request by porras**
Note that specifying an email in the build config WILL take precedence over unsubscribing. Discuss if that's the right behaviour of the feature.

Fixes https://github.com/travis-pro/team-teal/issues/2780.

### CODE REVIEW

**Comment by svenfuchs** [comment]
> Note that specifying an email in the build config WILL take precedence over unsubscribing. Discuss if that's the right behaviour of the feature.

I think it very much is. The build config is a lot more specific (per repo, branch, individual commits) and as such should overwrite a more generic "global" per-user setting.

👍

**Comment by carlad** [comment]
I agree with @porras too. Anything manually configured in the travis.yml file, even if the customer is unsubscribed in the UI.
If a customer is confused about why they keep getting emails, it will be easy to identify the issue by looking at their .travis.yml and getting them to remove any manual confiuguration. We can also add this note to our docs.
@joshk thoughts?

**Comment by joecorcoran** [comment]
Although it's important to note that this is not the global "no emails ever please" feature – it's the "specifially unsubscribe me from this repo" feature. I still think it's correct that the .travis.yml takes precedence though.

**Comment by porras** [comment]
I'm mergin then!

**Comment by joshk** [comment]
@porras @joecorcoran Thank you for this PR and the merge. 

I think we should amend the email template to mention that the email address was defined in the `.travis.yml`, and remove the unsubscribe link.

Thoughts?

**Comment by rwrede** [comment]
Would it also be a good idea to have some hint on the emails settings page where the configuration in travis.yml is overriding the status displayed in the UI? Could mean less support requests and less confusion in general for the users.

**Comment by porras** [comment]
@rwrede I think that would not be possible because while the settings are independent, we send a single email to all the recipients. Example: both your email and mine are in the config, so we both get the email regardless of the UI setting. I'm subscribed in the UI, you are unsubscribed, what should the email say?

Of course this would be possible if we change this so that we send separate emails to each person but currently that's a relatively big change I think.

**Pull request merged**
